### ISSUE TITLE
Bitcoin Price Widget

### ISSUE THREAD

**Issue by sunnankar** [sunnankar/wuc-new#3]
The price widget is customized with: 'Powered by: WeUseCoins.com' with the URL: http://www.weusecoins.com/en/bitcoin-price.html

To preview new page: http://www.weusecoins.org/en/bitcoin-price

For some reason the widget does not seem to embed well in Markdown.

However, the two lines of embed code from the original project at not customized. It would be good to get this fixed so we can include the two lines of embed code so others can embed the price widget and direct traffic back to this beginner's site.

Example: https://btcquote.com/

**Comment by sunnankar** [comment]
Thanks to @teneighty for getting the widget done with USD

Other currencies would be great. I think priority would be EUR, YUAN, GBP, C$, A$, YEN, Swedish Krona then South Korean Won. The formatting on the /de/, /fr/, /nl/ and /ja/ pages might take some work to embed widgets on the homepage. Would be good to keep the linkback in the widgets to: /en/bitcoin-price regardless of currency.

https://bitpay.com/bitcoin-exchange-rates

Not sure if it could have all three prices though if pulling from Bitpay's feed. Perhaps draw the price feeds from Kraken?

**Comment by teneighty** [comment]
No problem.

I am happy to look into getting more exchanges setup. We could use bitpay. I know bravenewcoin or coinbase supply all major exchange rates. Kraken is an option too. We might have to setup an separate server such as api.weusecoins.com to proxy those quotes. I'll get you more info first though.

**Comment by sunnankar** [comment]
Might be best to just use Bitpay. I would like to keep the Github Pages hosting since that keeps things as simple as possible.

**Comment by teneighty** [comment]
You got it. Right now the widget is still built off of firebase. I look into using Bitpay.
