### ISSUE TITLE
BitConnect ponzi in altcoins

### ISSUE THREAD

**Issue by ffmad** [sunnankar/wuc-new#659]
There is some shady coins in altcoins, but this one is quite above them

It's also quite dead

![2468d5fe600d808748b18d707b0071f4](https://user-images.githubusercontent.com/1488633/87014737-d50b5400-c1cc-11ea-9ac5-cb540d8c94d4.png)

**Comment by sunnankar** [comment]
Thanks @ffmad. Updated. Please feel free to submit any PRs for others.

<img width="721" alt="bitconnect" src="https://user-images.githubusercontent.com/4149214/87192225-4ae9eb00-c2b3-11ea-975d-d67b84c25940.png">

**Comment by ffmad** [comment]
Other coins seems to use that page for promotion, even though those are quite fishy.

Also, I've seen that ShadowCash page is still there, but Particl isn't (created from the swap of ShadowCash). Would it be possible to add the Particl page? (particl.io)

What I think would be good is to have a "Coins graveyard" page for deads coins, to put scams like BitConnect and old coins like ShadowCash that were replaced with new project.

**Comment by sunnankar** [comment]
Those are great ideas, especially the graveyard, and any pull requests to update the page so it is more useful and accurate would be greatly appreciated.

**Comment by ffmad** [comment]
Would you like to have a pull request with thoses changes, like coin graveyard?

**Comment by sunnankar** [comment]
@ffmad Sure, if you think you could get it put together and have it work well. There is a lot of work that could be done to make WUC a better resource for everyone. Any pitching in is greatly appreciated.

**Comment by ffmad** [comment]
I don't really have time right now, but we could have a discussion about this mid-august
